### ISSUE TITLE
Error Received 

### ISSUE THREAD

**Issue by Ashroyal** [kshcherban/acme-nginx#30]
Feb 24 09:06:37 Trying to register account key
Feb 24 09:06:38 Already registered!
Feb 24 09:06:38 Requesting challenge
Feb 24 09:06:39 Adding nginx virtual host and completing challenge
Feb 24 09:06:39 Creating file /etc/nginx/sites-enabled/0-letsencrypt.conf
Feb 24 09:06:39 Error adding virtual host ValueError max() arg is an empty sequence

**Comment by kshcherban** [comment]
Hello,

Is nginx running? Can you please post output of `ps -o ppid= -C nginx`?

**Comment by kshcherban** [comment]
@Ashroyal any progress on getting more debug info for me? You can check script yourself to see what may be wrong in your setup.
https://github.com/kshcherban/acme-nginx/blob/master/acme_nginx/client.py#L27-L35

**Comment by gucharbon** [comment]
I have the same issue.

First of all if `"/etc/nginx/sites-enabled"` is not an existing directory it will not be created and throw off an error : 
` Error adding virtual host IOError [Errno 2] No such file or directory: '/etc/nginx/sites-enabled/0-letsencrypt.conf'`

After creating this directory with `mkdir -p /etc/nginx/sites-enabled` I retried a simple 
`acme-nginx -d mydomain.fr`

And I got this error : 

`ps: unrecognized option: C`

I guess it's because I'm on Alpine-linux and `ps -o ppid= -C nginx` is not supported. 

Any guess on how bypass this error ?

**Comment by kshcherban** [comment]
@gucharbon please install `procps` package to have linux compatible ps util.
```
apk update
apk add procps
```
