### ISSUE TITLE
Installting as root broke pip3 on ub 20.04

### ISSUE THREAD

**Issue by tamone** [kshcherban/acme-nginx#64]
Hello,

After a root install with "pip3 install acme-nginx", pip/pip3 is no longer working and raises a long error message ending with:

 AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

Running on ubuntu 20.04. The previous command was to install pip3:

 apt install python3-pip

Cannot restore a working pip/pip3 removing and reinstalling the package python3-pip.

This was reproduced on 2 different machines.

This message may be also related to third party modules pyOpenSSL and cryptography (https://github.com/pyca/pyopenssl/issues/1114) , and should be reverted, as advertised, be going back to cryptography < v38 or < 37. But to do this pip is indicated necessary.

We cannot remove python3 completely from the system as the OS might be needing it.

How to uninstall acme-nginx, with all the modules to restore pip3 functionality ?

**Comment by leadrien** [comment]
Hi,
This is due to pyopenssl not pinning cryptography version (https://github.com/pyca/pyopenssl/issues/1143)
You can manually remove cryptography
On Ubuntu 20.04:
`rm -r /usr/local/lib/python3.8/dist-packages/cryptography*`
And install the last compatible version:
`pip3 install cryptography==37.0.3`

**Comment by kshcherban** [comment]
@leadrien thank you, will test and update pip package.
